version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
  api:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - 3000:3000
      - 4000:4000
    environment:
      - PORT=4000
      - DATABASE_URL=db
    depends_on:
      - db
